name: CI-CD

on:
  push:
    branches: ["main"]
  # workflow_dispatch: pode disparar manual também
  workflow_dispatch:


jobs:
  CI:  
    # runs-on: aonde o job vai ser executado, nesse caso no ambiente linux
    runs-on: ubuntu-latest
    steps:
      # run pode ser bash (?) código python, power shell
      - run: echo "Obter o código"
      - run: echo "Executar o Docker build"
      - run: echo "Enviar a imagem para o Docker Hub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter o código"
      - run: echo "Configurar o Kubeconfig"
      - run: echo "Executar o apply"
